services:
  frontend:
    image: ${DOCKER_REGISTRY}/cosc-349-a2/frontend
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    restart: always
    ports:
      - 80:80
    networks:
      - app_network
  api:
    image: ${DOCKER_REGISTRY}/cosc-349-a2/api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network

networks:
  app_network:
