services:
  frontend:
    image: ${DOCKER_REGISTRY}/online-notepad/frontend
    restart: always
    ports:
      - 80:80
      
  api:
    image: ${DOCKER_REGISTRY}/online-notepad/api
    restart: always
    ports:
      - 3001:3001
    environment:
      AWS_USER_POOL_ID: ${AWS_USER_POOL_ID}
      AWS_CLIENT_ID: ${AWS_CLIENT_ID}
      DB_HOST: ${POSTGRES_IP}
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: postgres